### ISSUE TITLE
Umbrella - Productionize STAR change-over-time graphs

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#2]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/413
- [x] Add STAR math
- [x] Make it navigable
- [ ] Some test coverage
- [ ] Improve STAR reading demo data so we can test locally
- [ ] Add option to clear filters
- [ ] Fix line interpolation issues
- [ ] Investigate reading data points that are close in time, but very different scores (eg., https://somerville.studentinsights.org/students/197?column=profile)
- [ ] update charts to show homeroom names
- [ ] precompute as much data as possible, to speed up server-side load times
- [ ] add axis labels, possibly legends (see https://github.com/studentinsights/studentinsights/issues/79#issuecomment-184983093)

**Comment by kevinrobinson** [comment]
There's some great ideas from a feedback session with Mohan from at Code for Boston here: https://github.com/studentinsights/studentinsights/issues/79#issuecomment-184983093

**Comment by kevinrobinson** [comment]
Capturing some conversations with @jgeiser this morning:

Jill's been gathering and entering a bunch of STAR data manually into a spreadsheet, to see how students have progressed over the last few assessments.  She's looking at every student, from 2nd-8th grade and records their grade-level equivalent.  She did this last fall, and is working on the winter scores now.  She wants to look at this by classroom.

She's looking for where there's a decline, whether it's in one class, whether a particular group of students went down, so she can talk to the teacher and learn more.  Sometimes there are issues with administering the test.  She wants to do this for both reading and math, but starts with reading since it is administered first.

We talked about the prototype charts that use percentiles - Jill said she always want to look at this as grade-level equivalent but that's just her and other principals might not.  She does something similar with DIBELs, starting at performance and then maybe digging deeper.

**Comment by alexsoble** [comment]
Don't think we're actively pushing forward on this @kevinrobinson, mind if I close it?

**Comment by kevinrobinson** [comment]
@alexsoble closing!
