### ISSUE TITLE
Umbrella - deploy at second school (West Somerville)

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#332]
## Second school deployment 

___Note___: "WSNS" => "West Somerville Neighborhood School"

### Human

+ [x] Onboarding checklist for new schools #278

### Data

+ [x] Double check X2/Aspen staff data at West Somerville #293 
+ [x] Debug data import process for West Somerville #333 
+ [x] Double check WSNS data — did in person with Uri and Kathleen April 14
+ [x] Add educator permissions from Uri to the DB

### Code / Design

+ As a school-based staff member:
  + [x] I should see only students from my school when using the student search bar (fixed by #336)
  + [x] When I click the "school overview", "STAR Math", and "STAR Reading" tabs, I should see pages showing the correct students for my school and authorization level
  + [x] I should be able to visit the student profile for any student at my school if I have the appropriate permissions (fixed by #336)
  + [x] I should not be able to visit the profiles of students at other schools (fixed by #336)
  + [x] When adding a staff member to a student Service record, I should see only staff members from my school in the dropdown list (fixed via ##339)

**Comment by alexsoble** [comment]
Pulled the WSNS data into the production site.

Clicked around to do some manual QA. School overview page took a long time to load but the data looked solid. Homeroom and profile pages loaded without incident. STAR Math / Reading overview pages took a very long time to load and then threw Application Errors due to request timeout.

Ran the precompute tasks to try to speed up the overview page, got an error:

```
2016-04-13T19:31:42.857847+00:00 app[run.3299]: ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_precomputed_query_docs_on_key"
2016-04-13T19:31:42.857198+00:00 app[run.3299]: DETAIL:  Key (key)=(precomputed_student_hashes_1460505600_) already exists.
```

Will investigate this!

**Comment by alexsoble** [comment]
@kevinrobinson precomputing == 🆒 

WSNS school overview page load before precompute:

```
Completed 200 OK in 19566ms (Views: 625.3ms | ActiveRecord: 7498.1ms)
```

WSNS school overview page load after precompute:

```
Completed 200 OK in 868ms (Views: 267.7ms | ActiveRecord: 139.9ms)
```

School overview page renders snappily, STAR Math and Reading pages take around ~10s but they load consistently and don't throw timeout errors.

**Comment by alexsoble** [comment]
We now have two user accounts set up for WSNS:

1. Principal Kathleen Seward. Kathleen sat down with Uri Harel and me yesterday to review the app, look for any bugs, and discuss rolling out to WSNS.
2. School Counselor Les Larty. Les is doing the same review and QA remotely. 

This coming week is spring break. Near the end of spring break week I'll load all the appropriate educator permissions into the app for WSNS. When they return from break any WSNS staff member will be able to log in, use the app, and take notes during SST / MTSS meetings at WSNS.

**Comment by alexsoble** [comment]
WSNS is up and running on Student Insights . . . closing.
