### ISSUE TITLE
Investigate data irregularities with attendance

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#4]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/96

**Comment by alexsoble** [comment]
## TODO 

+ [ ] Handle past attendance records with invalid dates
+ [ ] Investigate {absences} + {tardies} != 100% of events

**Comment by alexsoble** [comment]
First, investigating attendance events that are neither absences not tardies.

Wrote a script to analyze the attendance data dump from X2: f49bd4972308b6e24210bc5b6a79b5715274653f

Ran this against the first 100,000 lines (out of 361,099) because the CSV parser hits malformed rows after that. So this analysis should be considered ___incomplete___, but it's a start.

Output from the script (aggregates only, of course):

```
COUNTS FOR INDICATOR == "1" (TRUE)

att_tardy_ind  =>  38205 out of 99983
att_tardy_ind_02  =>  0 out of 99983
att_dismissed_ind  =>  10280 out of 99983
att_dismissed_ind_02  =>  0 out of 99983
att_excused_ind  =>  1091 out of 99983
att_excused_ind_02  =>  0 out of 99983
att_absent_ind  =>  49963 out of 99983
att_absent_ind_02  =>  0 out of 99983


COUNTS FOR INDICATOR == "0" (FALSE)

att_tardy_ind  =>  61778 out of 99983
att_tardy_ind_02  =>  99983 out of 99983
att_dismissed_ind  =>  89703 out of 99983
att_dismissed_ind_02  =>  99983 out of 99983
att_excused_ind  =>  98892 out of 99983
att_excused_ind_02  =>  99983 out of 99983
att_absent_ind  =>  50020 out of 99983
att_absent_ind_02  =>  99983 out of 99983
```

From the X2 data dictionary:

ATT_ABSENT_IND => Absent?
ATT_ABSENT_IND_02 => Absent PM?
ATT_DISMISSED_IND => Dismissed?
ATT_DISMISSED_IND_02 => Dismissed PM?
ATT_EXCUSED_IND => Excused?
ATT_EXCUSED_IND_02 => Excused PM?
ATT_TARDY_IND => Tardy?
ATT_TARDY_IND_02 => Tardy PM?

## What this means

* First of all: nothing conclusive, because we still have to analyze the remainder of the data

* PM columns all blank so far

* Small number of excused absences/tardies; my intuition is that these events are likely low priority to import because they don't necessarily indicate a student in need of extra support

* For the `att_dismissed_ind` column: need to talk to teachers, principals, and/or school secretaries about what this column represents in practice how it fits into the work

**Comment by alexsoble** [comment]
## Attendance dump analysis: indicators

```
COUNTS FOR INDICATOR == "1" (TRUE
att_tardy_ind         => 796938 out of 1875435    42.49
att_tardy_ind_02      => 0 out of 1875435         0
att_dismissed_ind     => 180567 out of 1875435    9.63
att_dismissed_ind_02  => 0 out of 1875435         0
att_excused_ind       => 84271 out of 1875435     4.49
att_excused_ind_02    => 0 out of 1875435         0
att_absent_ind        => 856361 out of 1875435    45.66
att_absent_ind_02     => 0 out of 1875435         0


Tardies + Absences:                               88.15%
Tardies + Absences + Dismissed:                   97.78%
Tardies + Absences + Dismissed + Excused:         102.27%


COUNTS FOR INDICATOR == "0" (FALSE
att_tardy_ind         => 1078497 out of 1875435   57.50%
att_tardy_ind_02      => 1875435 out of 1875435   100%
att_dismissed_ind     => 1694868 out of 1875435   90.37%
att_dismissed_ind_02  => 1875435 out of 1875435   100%
att_excused_ind       => 1791164 out of 1875435   95.50%
att_excused_ind_02    => 1875435 out of 1875435   100%
att_absent_ind        => 1019074 out of 1875435   54.34%
att_absent_ind_02     => 1875435 out of 1875435   100%
```

## What I think this means

+ Confirm that PM indicators (i.e. `att_absent_ind_02`, `att_tardy_ind_02`) aren't used

+ Confirm that excused attendance events are a small percentage of total

+ Still need to clarify meaning of `att_dismissed_ind` (9.63% of total)

+ Tardies + Absences + Dismissed + Excused adds up to slightly more than 100%, meaning that there must be a small number of events that are flagged as TRUE for more than one indicator

**Comment by alexsoble** [comment]
## New TODO

+ [ ] Get in touch with Marie and Jill from the Healey about `att_dismissed_ind`
+ [ ]  Investigate {tardies} + {absences} + {dismissed} + {excused} > 100%

  + Not a high priority compared to other data quality issues

  + But could be useful to discover which events are tagged with more than one indicator and how we might want to handle them

  + My guess: these are {absent} + {excused}, {tardy} + {excused}

**Comment by alexsoble** [comment]
Description of what `att_dismissed_ind` means, from the secretary at the Healey school:

> Dismissed means that students have left school early.  Parents come in and dismiss them.  I should say everyday at least 4-5 students are dismissed for either appointments, they are sick, or who knows what.

Sounds to me like a `dismissed` indicator is a lower risk signal than absence or tardy. Because of that, integrating `dismissed` information into Student Insights seems like a lower priority.

**Comment by alexsoble** [comment]
## Summary

+ Attendance rows with dates in the future or far past are excluded during data import (#73)

+ Enable parsing of full attendance data dump by handling malformed CSV rows 

  + General `AnalyzeStudentAttendance` class: `lib/analyze_student_attendance.rb`

  + Script used for this particular issue: `scripts/data/analyze_student_attendance.rb`

+ Confirmed that the "Absent PM?", "Dismissed PM?", "Excused PM?", and "Tardy PM?" columns are not used in Somerville's X2 instance

+ Clarified the meaning of the `dismissed` indicator, see comment above

+ Discovered that the Tardy / Absence / Dismissed / Excused attendance indicators are not mutually exclusive, broke off into #127

**Comment by kevinrobinson** [comment]
@alexsoble awesome summary! :+1:
