### ISSUE TITLE
Umbrella - Redesign student profile page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#5]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/373

The graphs are the first thing the user sees – but they're not necessarily the most useful!

Mockups v1:
[profile.redesign.mockups (2).pdf](https://github.com/studentinsights/studentinsights/files/122154/profile.redesign.mockups.2.pdf)

Mockups v2:
[profile.redesign.v2 (3).pdf](https://github.com/studentinsights/studentinsights/files/122155/profile.redesign.v2.3.pdf)

Some options for next steps:
+ [x] Build the interventions panel
+ [x] Add tab selection by clicking on panels
+ [x] ELA: Add STAR and MCAS charts
+ [x] Improve layout and styling for demographics section
+ [x] Improve header styling (@BWieber in https://github.com/studentinsights/studentinsights/issues/93)
+ [x] Math: Add STAR and MCAS charts (@erose)
+ [x] Attendance: Add in charts
+ [x] Attendance: Add in text summaries for behavior incidents
+ [x] Attendance: Improve styling for behavior incidents (@bw120 in https://github.com/studentinsights/studentinsights/pull/139)
+ [x] ELA: Add DIBELS numbers (https://github.com/studentinsights/studentinsights/issues/23 and https://github.com/studentinsights/studentinsights/pull/283 and https://github.com/studentinsights/studentinsights/issues/291)
+ [x] Profile: design iterations, add full timeline view (@erose in https://github.com/studentinsights/studentinsights/issues/117)

Notes and interventions flow (@kevinrobinson):
+ [x] Design: structure interventions by what outcomes they're attempting to move?
+ [x] Improve initial rendering for notes
+ [x] Add UI for adding a note, endpoint
+ [x] Improve rendering for new interventions and progress notes
+ [x] Add UI for adding an intervention, endpoint (@BWieber and @kevinrobinson in https://github.com/studentinsights/studentinsights/issues/115)

Data questions (Related: https://github.com/studentinsights/studentinsights/issues/4 and https://github.com/studentinsights/studentinsights/issues/1):

+ [x] Fix bug with assessment dates in demo data
+ [x] Investigate nil STAR assessments (https://github.com/studentinsights/studentinsights/issues/91)

Action items from @jgeiser's feedback on 2/12:
+ [x] Show the type of note (eg., SST meeting)
+ [x] Move 51a from notes to services
+ [x] Finish adding ability to save services (https://github.com/studentinsights/studentinsights/issues/115)
+ [x] Add in read-side translation for older student notes
+ [x] Add in read-side translation for interventions
+ [x] Add in read-side translation for progress notes
+ [x] Fix layout and styling bugs on Internet Explorer
+ [x] Improve how long it takes to load the overview page (https://github.com/studentinsights/studentinsights/issues/3)

Updates to the overview page:
+ [x] Filter for services, show service count in table (https://github.com/studentinsights/studentinsights/pull/212)
+ [x] Filter for event_notes (https://github.com/studentinsights/studentinsights/pull/221)

Final set of improvements to close this issue:
+ [x] Simplify date formats and transformations between them
+ [x] Add ACCESS data to the page (https://github.com/studentinsights/studentinsights/issues/292)
+ [x] Show multiple years for absences, tardies, behavior incidents (currently just one year, may require precomputing) (https://github.com/studentinsights/studentinsights/pull/324 and https://github.com/studentinsights/studentinsights/issues/290)
+ [x] Remove v1 profile code paths (https://github.com/studentinsights/studentinsights/issues/211)

Future enhancements, split out to standalone issues:
+ [ ] Add grade-level equivalent for STAR scores in ELA and Math (https://github.com/studentinsights/studentinsights/issues/229)
+ [ ] Add ability to edit and delete notes (https://github.com/studentinsights/studentinsights/issues/228)

**Comment by kevinrobinson** [comment]
Some WIP code is here: https://github.com/codeforamerica/somerville-teacher-tool/compare/master...kevinrobinson:feature/student-profile-v2-alpha?expand=1.  Updating local demo data will be helpful for this feature too, but current status is that it looks like this:

<img width="1420" alt="screen shot 2016-02-02 at 6 42 13 pm" src="https://cloud.githubusercontent.com/assets/1056957/12768307/ccc5b976-c9dc-11e5-907c-3225cbad27f5.png">

**Comment by kevinrobinson** [comment]
FYI erose, madrigalbrian, sentientmachine, alexsoble, bryanhirsch

I pushed some more commits with progress here to https://github.com/codeforamerica/somerville-teacher-tool/compare/master...kevinrobinson:feature/student-profile-v2-alpha?expand=1.  I'll be working on it more next week, including Tuesday at Code For Boston, aiming to ship a prototype for feedback next week and a trial run next Friday (unless we get another snow day :)).

**Comment by kevinrobinson** [comment]
We tested this out in an SST meeting this morning, and here's the roughly prioritized takeaways after talking with @jgeiser.

+ [ ] Show the type of note (eg., SST meeting)
+ [ ] Move 51a from notes to services
+ [ ] Add grade-level equivalent to the summary sections for ELA and Math
+ [ ] Finish adding ability to save services
+ [ ] Fix layout and styling bugs on Internet Explore
+ [ ] Improve how long it takes to load the overview page
+ [ ] Add the rest of the of academic charts
+ [ ] Add ability to edit and delete notes

**Comment by kevinrobinson** [comment]
After some out-of-band email conversations, the product cutover is happening in https://github.com/studentinsights/studentinsights/pull/203, which will help with getting feedback from some new users.  This will simplify the onboarding experience for those new users, and let us get feedback from them without them having to hop through the the v1 profile page and then an extra click to the v2 profile page.

The remaining improvements here are all important and it doesn't affect the priorities for the remaining items on this issue - let's get them done!

**Comment by erose** [comment]
I checked off some boxes that pointed to closed issues.

What does "Show multiple years for absences, tardies, behavior incidents (currently just one year, may require precomputing)" refer to -- is that talking about the graphs or sparklines? Graphs are all last 4 years and the sparklines are all-time, I thought.

**Comment by kevinrobinson** [comment]
@erose Awesome!  That item is talking about the graphs and sparkelines - they used to just show one year and just zeros for earlier years but that has been done.  I updated that and all the others I could find to link to the issues that closed that work so this should be up-to-date now.

Since we're using the "Milestone" feature now, I moved the only two items left to the bottom, since they are not critical and are already split out into their own issues as enhancements.  I also cut "Investigate multiple recent STAR assessments (need new test case)" since we don't have a test case for this.

That means we can close this beast out now (thanks to much hard work from you, @bw120 and @BWieber in particular!).  Would you do the honors? :)

**Comment by erose** [comment]
![pow-weddings](https://cloud.githubusercontent.com/assets/1514487/14946156/fd78bbae-0feb-11e6-9e16-67226f8d625e.jpg)
