### ISSUE TITLE
Umbrella - Create SPED referral packet

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#8]
From https://github.com/codeforamerica/somerville-teacher-tool/issues/100

Teachers and administrators want to be able to create a SPED referral packet from all the the information in Student Insights.  This is a laborious manual process now, across several computer and paper data systems that we can help automate.

This will likely be a PDF, and will require working closely with school partners to iterate on the exact requirements.  https://github.com/codeforamerica/somerville-teacher-tool/issues/100 has more background on the types of information that might be important.
#### Rough first steps
- [x] https://github.com/studentinsights/studentinsights/pull/137 - "Hello world" PDF (@eudaimonious)
- [x] Verify that download UX is good on Windows IE (@kevinrobinson)
- [x] Add raw unstyled data from text mock (https://github.com/studentinsights/studentinsights/pull/165)
- [ ] Add info in the 'Additional Notes' section https://github.com/studentinsights/studentinsights/issues/497 (@bwieber)
#### Research and design steps
- [x] Get feedback from school folks on text mock in https://github.com/studentinsights/studentinsights/pull/165
#### Work based on feedback from our end user
- [x] Add birth date https://github.com/studentinsights/studentinsights/issues/498 (@eudaimonious)
- [ ] Academic Assessments should be grouped by test/subject with ACCESS at the top. https://github.com/studentinsights/studentinsights/issues/499 (@eudaimonious)
- [ ] The DIBELS test should show scores not percentile rankings https://github.com/studentinsights/studentinsights/issues/500 (@iqnivek)
- [ ] Add ELL Status under Language https://github.com/studentinsights/studentinsights/issues/501
#### Add a button so folks can access it!
- [x] Add a button to the profile to access the PDF. Be very explicit about the beta nature of this feature. https://github.com/studentinsights/studentinsights/issues/502 (@eudaimonious)
##### Open questions

Do we need this additional information?  Is it new, or is it possibly available in district systems like Aspen already?
- Prior school enrollments?
- Retention?
- Grades?
- Report cards?
- In-school and out-of-school suspensions?
- Health, medical, nursing?
- Specific evidence of RTI?

After that, we can learn more about what else we need here, whether it involves adding a separate UI up front to ask for a few details, whether we want to record all packets that are generated for the case history, or whatever else comes up.  It'll be easier to do that working with school folks as referrals come up, so iterations here might require a little more communication.

**Comment by kevinrobinson** [comment]
@eudaimonious is helping with this tonight!

**Comment by kevinrobinson** [comment]
UX on IE11 on Windows 8 looks good!

<img width="1262" alt="screen shot 2016-03-02 at 9 26 37 am" src="https://cloud.githubusercontent.com/assets/1056957/13463141/e921b4ca-e058-11e5-800d-69a6475ff278.png">

via browserstack.com

**Comment by eudaimonious** [comment]
I've begun putting the data from the [draft mock-up](https://github.com/studentinsights/studentinsights/pull/165/files) into the pdf. So far I've noticed that we're missing birthdate and, unless I'm missing something here, we're missing a piece of information needed to calculate the attendance percentage ("total number of school days in the school year").

**Comment by alexsoble** [comment]
We have a V1 of this shipped and in production! By @jhilde.
